"""Tests for the `.fdx` parser (Layer 1.1).

Two kinds of fixture are used deliberately:

- `sample-0*.fdx` are real Final Draft output, downloaded unmodified. They prove
  the parser handles files Final Draft actually writes, including the paragraphs
  outside `<Content>` that a naive XPath would ingest as screenplay.
- `feature-draft-1.fdx` and `small-draft-1.fdx` are generated by
  `scripts/make_fixture.py` with production structure the public samples lack:
  scene numbers, `34A` inserts, `OMITTED` scenes and revision marks.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from bluepages.events import CollectingStream, EventKind
from bluepages.model import ElementType, InteriorExterior, TimeOfDay
from bluepages.parse import UnsupportedFormatError, parse_script
from bluepages.parse.fdx import FdxParseError, parse_fdx, parse_fdx_string

FIXTURES = Path(__file__).parent.parent / "fixtures"


@pytest.fixture(scope="module")
def feature():
    return parse_fdx(FIXTURES / "feature-draft-1.fdx")


@pytest.fixture(scope="module")
def small():
    return parse_fdx(FIXTURES / "small-draft-1.fdx")


class TestRealFinalDraftFiles:
    """Against unmodified Final Draft output."""

    @pytest.mark.parametrize("name", ["sample-01", "sample-02", "sample-03"])
    def test_parses_without_error(self, name):
        sp = parse_fdx(FIXTURES / f"{name}.fdx")
        assert sp.scene_count >= 1

    def test_typed_elements_need_no_heuristics(self):
        sp = parse_fdx(FIXTURES / "sample-01.fdx")
        types = {e.type for s in sp.scenes for e in s.elements}
        assert ElementType.ACTION in types
        assert ElementType.CHARACTER in types
        assert ElementType.DIALOGUE in types
        assert ElementType.PARENTHETICAL in types

    def test_nine_revision_sets_are_read(self):
        """Blue, Pink, Yellow, Green... the paper protocol this automates."""
        sp = parse_fdx(FIXTURES / "sample-01.fdx")
        assert len(sp.revisions) == 9
        assert sp.revisions[1].name == "Blue"
        assert sp.revisions[2].name == "Pink"

    def test_unnumbered_draft_warns_about_alignment(self):
        """A draft with no scene numbers degrades alignment. Say so loudly."""
        stream = CollectingStream()
        sp = parse_fdx(FIXTURES / "sample-02.fdx", stream=stream)
        assert not sp.has_scene_numbers
        warnings = stream.of_kind(EventKind.PARSE_WARNING)
        assert any("alignment" in w.message for w in warnings)


class TestContentScoping:
    """The trap: `<Paragraph>` also lives outside `<Content>`."""

    def test_page_furniture_is_not_screenplay(self, feature):
        """Headers and watermarks must never become action lines."""
        text = " ".join(e.text for s in feature.scenes for e in s.elements)
        assert "PAGE HEADER" not in text
        assert "WATERMARK" not in text

    def test_title_page_is_not_a_scene(self, feature):
        headings = [s.heading for s in feature.scenes]
        assert "Written by A. Writer" not in headings


class TestSceneNumbers:
    def test_every_scene_numbered(self, feature):
        assert feature.has_scene_numbers
        assert len(feature.numbered_scenes) == feature.scene_count

    def test_file_order_matches_numeric_order(self, feature):
        """Inserts must not break the sequence: ... 9, 9A, 10 ..."""
        nums = [s.number for s in feature.numbered_scenes]
        assert nums == sorted(nums)

    def test_inserts_are_detected(self, feature):
        inserts = [s for s in feature.scenes if s.number and s.number.is_insert]
        assert inserts
        assert all(s.number.suffix or s.number.prefix for s in inserts)

    def test_lookup_by_number(self, small):
        scene = small.scene("3")
        assert scene is not None
        assert scene.number is not None
        assert scene.number.number == 3


class TestOmittedScenes:
    """Scenes are marked OMITTED, never deleted. That is why numbers are stable."""

    def test_omitted_scenes_detected(self, feature):
        assert feature.omitted_scenes

    def test_omitted_scene_keeps_its_number(self, feature):
        for scene in feature.omitted_scenes:
            assert scene.number is not None

    def test_omitted_scene_has_no_body(self, feature):
        for scene in feature.omitted_scenes:
            assert scene.elements == []

    def test_omitted_scene_does_not_warn(self, feature):
        """A bare OMITTED has no slugline. Correct, not malformed."""
        stream = CollectingStream()
        parse_fdx(FIXTURES / "feature-draft-1.fdx", stream=stream)
        messages = [w.message for w in stream.of_kind(EventKind.PARSE_WARNING)]
        assert not any("INT/EXT" in m for m in messages)


class TestRevisionTracking:
    def test_revised_scenes_detected(self, feature):
        assert any(s.revised for s in feature.scenes)

    def test_revision_marks_resolve_to_named_sets(self, feature):
        """RevisionID 2 must report as "Pink", not as a bare integer."""
        marked = [
            m
            for s in feature.scenes
            for e in s.elements
            for m in e.revision_marks
        ]
        assert marked
        assert any(m.name for m in marked)

    def test_unrevised_runs_do_not_mark(self, feature):
        """RevisionID="0" is the default and means unrevised."""
        clean = [s for s in feature.scenes if not s.revised]
        assert clean
        for scene in clean:
            assert all(not e.revision_marks for e in scene.elements)

    def test_split_runs_are_reassembled(self):
        """A paragraph split across runs is one element, marked if any run is."""
        xml = """<?xml version="1.0" encoding="UTF-8"?>
<FinalDraft DocumentType="Script" Version="5">
  <Content>
    <Paragraph Number="1" Type="Scene Heading">
      <Text RevisionID="0">INT. KITCHEN - DAY</Text>
    </Paragraph>
    <Paragraph Type="Action">
      <Text RevisionID="0">She sets the envelope down </Text>
      <Text RevisionID="2">and slides it across the table.</Text>
    </Paragraph>
  </Content>
  <Revisions><Revision ID="2" Name="Pink" Color="#FF00FF"/></Revisions>
</FinalDraft>"""
        sp = parse_fdx_string(xml)
        action = sp.scenes[0].elements[0]
        assert action.text == "She sets the envelope down and slides it across the table."
        assert action.revised
        assert action.revision_marks[0].name == "Pink"


class TestSceneMetadata:
    def test_heading_fields_parsed(self, small):
        scene = small.scenes[0]
        assert scene.int_ext is not InteriorExterior.UNKNOWN
        assert scene.location
        assert scene.time_of_day is not TimeOfDay.UNKNOWN

    def test_scene_properties_read(self, small):
        assert any(s.page for s in small.scenes)
        assert any(s.summary for s in small.scenes)

    def test_script_note_attached_to_scene(self, feature):
        """A note on a scene heading belongs to the scene, not to a paragraph."""
        noted = [s for s in feature.scenes if s.notes]
        assert noted
        assert "practical lamp" in noted[0].notes[0].text

    def test_title_from_title_page(self, feature):
        assert feature.title == "THE LONG ACRE"


class TestSpeakerResolution:
    def test_dialogue_carries_its_speaker(self, small):
        dialogue = [
            e for s in small.scenes for e in s.elements if e.type is ElementType.DIALOGUE
        ]
        assert dialogue
        assert all(e.speaker for e in dialogue)

    def test_contd_resolves_to_base_character(self, small):
        """MARY (CONT'D) speaking is MARY speaking."""
        speakers = {
            e.speaker for s in small.scenes for e in s.elements if e.speaker
        }
        assert all("CONT" not in (sp or "") for sp in speakers)

    def test_action_clears_the_speaker(self):
        """Dialogue after an action line must not inherit a stale speaker."""
        xml = """<?xml version="1.0" encoding="UTF-8"?>
<FinalDraft DocumentType="Script" Version="5">
  <Content>
    <Paragraph Number="1" Type="Scene Heading"><Text>INT. KITCHEN - DAY</Text></Paragraph>
    <Paragraph Type="Character"><Text>MAE</Text></Paragraph>
    <Paragraph Type="Dialogue"><Text>Hello.</Text></Paragraph>
    <Paragraph Type="Action"><Text>She leaves.</Text></Paragraph>
  </Content>
</FinalDraft>"""
        sp = parse_fdx_string(xml)
        action = next(e for e in sp.scenes[0].elements if e.type is ElementType.ACTION)
        assert action.speaker is None


class TestPreambleAndStructure:
    def test_fade_in_is_not_lost(self, feature):
        """Front matter before the first slugline attaches to scene 1."""
        first = feature.scenes[0]
        assert any("FADE IN" in e.text for e in first.elements)

    def test_scene_count_matches_headings(self, feature):
        assert feature.scene_count == 133

    def test_characters_collected(self, feature):
        assert "HARLAN" in feature.all_characters
        assert "MAE" in feature.all_characters


class TestErrorHandling:
    def test_missing_file(self, tmp_path):
        with pytest.raises(FdxParseError, match="not found"):
            parse_fdx(tmp_path / "nope.fdx")

    def test_wrong_root_element(self, tmp_path):
        p = tmp_path / "bad.fdx"
        p.write_text("<?xml version='1.0'?><NotFinalDraft/>", encoding="utf-8")
        with pytest.raises(FdxParseError, match="expected <FinalDraft>"):
            parse_fdx(p)

    def test_no_content_section(self, tmp_path):
        p = tmp_path / "empty.fdx"
        p.write_text(
            "<?xml version='1.0'?><FinalDraft DocumentType='Script'/>", encoding="utf-8"
        )
        with pytest.raises(FdxParseError, match="no <Content>"):
            parse_fdx(p)

    def test_unsupported_extension(self, tmp_path):
        p = tmp_path / "script.docx"
        p.write_text("x", encoding="utf-8")
        with pytest.raises(UnsupportedFormatError):
            parse_script(p)

    def test_pdf_routes_to_tier_2(self, tmp_path):
        """PDFs now reach the tier 2 parser, which reports its own errors.

        A truncated PDF is a PDF problem, not an unsupported format.
        """
        from bluepages.parse import PdfParseError

        p = tmp_path / "script.pdf"
        p.write_bytes(b"%PDF-1.4")
        with pytest.raises(PdfParseError):
            parse_script(p)

    def test_external_entities_are_not_resolved(self, tmp_path):
        """A script arriving from outside the production must not read our disk."""
        secret = tmp_path / "secret.txt"
        secret.write_text("TOPSECRET", encoding="utf-8")
        p = tmp_path / "xxe.fdx"
        p.write_text(
            f"""<?xml version="1.0"?>
<!DOCTYPE FinalDraft [<!ENTITY xxe SYSTEM "file://{secret.as_posix()}">]>
<FinalDraft DocumentType="Script">
  <Content>
    <Paragraph Number="1" Type="Scene Heading"><Text>INT. A - DAY</Text></Paragraph>
    <Paragraph Type="Action"><Text>&xxe;</Text></Paragraph>
  </Content>
</FinalDraft>""",
            encoding="utf-8",
        )
        sp = parse_fdx(p)
        text = " ".join(e.text for s in sp.scenes for e in s.elements)
        assert "TOPSECRET" not in text


class TestProgressEvents:
    """Layer 3.6: events are emitted while working, not after."""

    def test_scene_events_emitted(self, tmp_path):
        stream = CollectingStream()
        sp = parse_fdx(FIXTURES / "small-draft-1.fdx", stream=stream)
        assert stream.count(EventKind.SCENE_PARSED) == sp.scene_count

    def test_lifecycle_events(self):
        stream = CollectingStream()
        parse_fdx(FIXTURES / "small-draft-1.fdx", stream=stream)
        assert stream.count(EventKind.PARSE_STARTED) == 1
        assert stream.count(EventKind.PARSE_FINISHED) == 1

    def test_events_carry_structured_data(self):
        """The UI consumes fields, not prose."""
        stream = CollectingStream()
        parse_fdx(FIXTURES / "small-draft-1.fdx", stream=stream)
        event = stream.of_kind(EventKind.SCENE_PARSED)[0]
        assert "scene_number" in event.data
        assert "heading" in event.data


class TestRoundTrip:
    def test_model_survives_json(self, small):
        """Layer 4 persists this and Layer 7 ships it over the wire."""
        from bluepages.model import Screenplay

        restored = Screenplay.model_validate_json(small.model_dump_json())
        assert restored.scene_count == small.scene_count
        assert [str(s.number) for s in restored.scenes] == [
            str(s.number) for s in small.scenes
        ]
